### PR TITLE
Remove absolute directories on external program call paths.

### PR DESCRIPTION
**Pull request by FGrose**
Support the PATH environment variable for program calls.

This is untested for for kickstart.py, creator.py, live.py, edit-livecd, mkbackup, & mkbiarch.

### CODE REVIEW

**Comment by latot** [comment]
:O nice!

**Comment by Conan-Kudo** [comment]
@FGrose What did you test this with, then?

**Comment by FGrose** [comment]
@Conan-Kudo: I tested with my editliveos branch, https://github.com/FGrose/livecd-tools/tree/editliveos, (a pending, full feature replacement for edit-livecd).  It exercises fs.py, util.py, and portions of live.py, creator.py.

**Comment by FGrose** [comment]
So I'm sorry that I was not more explicit--this is only a partially complete patch--totally untested on the image creation side with kickstart.  It is something for someone to pick up and complete.  I have no experience using kickstart, so I defer to someone with more experience in that area of the code.

**Comment by FGrose** [comment]
I force pushed 4a743e8 in which I moved the new function `chroottypecheck()` to fs.py where it will be generally available.

**Comment by Conan-Kudo** [comment]
@FGrose Is this now deprecated with #67? If so, I'll close this.

**Comment by FGrose** [comment]
@Conan-Kudo : Yes, this is superseded by #67.  Merging that will ease the necessary testing.

**Pull request closed without merging**
