### PR TITLE
Support a flattened squashfs.img & non-standard image & overlay paths.

### PR DESCRIPTION
**Pull request by FGrose**
~~~~txt
  A simplified root filesystem structure may be provided for OverlayFS
overlays by squashing the root filesystem directly instead of squashing
an embedded image file at /LiveOS/rootfs.img.

  livecd-creator gets a new option --flat-squashfs;
  editliveos gets a new option --flatten-squashfs.
A kickstart entry of:
  bootloader --append='rd.live.overlay.overlayfs'
will trigger the flatten-squashfs option to package() and the
--flat-squashfs option to livecd-creator will insert that bootloader
append line argument into the boot configuration files.  Either option
is sufficient.

  Include /images in the installation to support propagation of the
image from the new installation and booting on alternate hardware.
  Include LICENSE and README files in the installation.

  dracut also supports non-standard rootfs.img and overlay paths.
Provide tooling to support those options in editliveos with
--rootfsimg <path path> and --overlay [<devspec>:]<pathspec> options.

  Support the refreshing of a running live booted LiveOS image by
deleting the image file and overlay after merging them in a new image
file and providing a new overlay for the next boot.
~~~~
This code was tested for _de novo_ LiveCD creation with the following command line:
 `$ sudo livecd-creator --config=/usr/share/doc/livecd-tools/livecd-fedora-minimal.ks --flat-squashfs`

Also:
#### README: Update to include liveimage-mount & editliveos tools.

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
Thanks for the changes!

**Comment by lzap** [comment]
Apologies for resurecting an old discussion, but image reduction is huge and I would like to use this for my CentOS7-based image. I can build the image with `--flat-squashfs` option however it does not boot up as kernel cannot find the root volume. I suppose I need to change kernel command line options which were `rootflags=loop root=live:/fdi.iso rootfstype=auto ro rd.live.image acpi=force rd.luks=0 rd.md=0 rd.dm=0 rd.lvm=0 rd.bootif=0` before the change. Can you help me finding correct ones? I tried `rd.live.overlay.overlayfs` without any luck. Thanks!

The git repo with the kickstart and build script is here: https://github.com/theforeman/foreman-discovery-image

**Comment by Conan-Kudo** [comment]
@lzap I'm not sure that dracut in CentOS 7 actually supported flattened squashfs. The feature was added to dracut 049 by @FGrose in https://github.com/dracutdevs/dracut/commit/789668deb3e6f8584ffab964d2204ddcb75f0a06 and that was not backported to RHEL 7 (presumably nobody asked for it there).

You have two options here:

* Backport the CentOS 8 dracut to CentOS 7 (this will likely work and give you everything you ask for)
* Upgrade your kickstart to CentOS 8 (this will definitely work and livecd-tools in EPEL 8 will work for you)

**Comment by lzap** [comment]
Thank you very much, I am not creating a BZ it's probably too late in the cycle. Upgrade to EL8 is planned later.

**Pull request merged**
