### PR TITLE
place efiboot.img and macboot.img in /isolinux

### PR DESCRIPTION
**Pull request by sobjerke**
#188 create efi image files under /isolinux, not /images

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
I think @FGrose changed this to match Lorax, it might be worth him looking at this...

**Comment by sobjerke** [comment]
Seems like the change happened in this commit back in 2019:
https://github.com/livecd-tools/livecd-tools/commit/e4c96c29bb53b741b82d9397a9c9e79a2557494c

However, when mkefiboot tries to create the image, the directory /images does not exist, and efiboot.img never gets created, resulting in iso image that is not bootable at all.

I can see two options here
1) make sure /images is created before mkefiboot is run (and update any other references to the path)
2) revert the change and put the files in /isolinux

**Comment by Conan-Kudo** [comment]
@sobjerke I would prefer a change to make it so that `/images` existed. Aligning with Lorax makes things less painful down the road.

**Comment by sobjerke** [comment]
@Conan-Kudo and @FGrose: Does this look like the correct place to create /images?

```
diff --git a/imgcreate/live.py b/imgcreate/live.py
index 673c54d..0eb6fdb 100644
--- a/imgcreate/live.py
+++ b/imgcreate/live.py
@@ -237,6 +237,7 @@ class LiveImageCreatorBase(LoopImageCreator):
             return

         # XXX-BCL: does this need --label?
+        makedirs(isodir + "/images")
         subprocess.call(["mkefiboot", isodir + "/EFI/BOOT",
                          isodir + "/images/efiboot.img"])

```

With this change and a modified version of #190 to reflect the changed path of efiboot.img, I am now able to create a live image of CentOS 8 that is bootable both via bios and efi.

If you agree, I will replace #189 with a new PR.

**Comment by mikhailnov** [comment]
This is also needed for ROSA

**Comment by Conan-Kudo** [comment]
Let's take this for now and fix it later.

**Pull request merged**
